### ISSUE TITLE
No color highlight for tags in xml files

### ISSUE THREAD

**Issue by febLey** [tinkertrain/panda-syntax-vscode#9]
Since the latest update tags in xml file don't have a color, I think they should look similar to html files.

![screen shot 2017-08-30 at 09 59 56](https://user-images.githubusercontent.com/1727958/29861599-13496c7e-8d6a-11e7-8a95-df80c5c6f8b4.png)

Language: XML, HTML
Raw File Contents:
```
<?xml version="1.0" encoding="UTF-8"?>
<xliff version="1.0">
  <file source-language="en" datatype="plaintext" original="messages" date="2014-09-04T18:16:21Z" product-name="razor">
    <header />
    <body>
      <trans-unit id="dceTitle">
        <source>Socialbar</source>
      </trans-unit>
      <trans-unit id="dceDescription">
        <source>Element with social icons</source>
      </trans-unit>
      <trans-unit id="title">
        <source>Title</source>
      </trans-unit>
    </body>
  </file>
</xliff>
```

**Comment by siamak** [comment]
@febLey We'll fix this issue in new version 👍

**Comment by siamak** [comment]
@febLey Sorry for delay to response. In new version (soon) we fix this issue.

**Comment by buianhthang** [comment]
fixed in #20

**Comment by matronator** [comment]
@anhthang Uhm, was this fix ever pushed to open-vsx? I'm using VSCodium and my XML files are still broken.
